#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BPAUTO_AVERAGE 1
#define CPTCFG_BPAUTO_NEW_LEDS 1
#define CPTCFG_BPAUTO_LEDS_CLASS 1
#define CPTCFG_BPAUTO_LEDS_TRIGGERS 1
#define CPTCFG_BPAUTO_CRYPTO_CCM 1
#define CPTCFG_BPAUTO_WANT_DEV_COREDUMP 1
#define CPTCFG_BPAUTO_BUILD_WANT_DEV_COREDUMP 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_MESH 1
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_BT_MODULE 1
#define CPTCFG_BT_BREDR 1
#define CPTCFG_BT_RFCOMM_MODULE 1
#define CPTCFG_BT_BNEP_MODULE 1
#define CPTCFG_BT_BNEP_MC_FILTER 1
#define CPTCFG_BT_BNEP_PROTO_FILTER 1
#define CPTCFG_BT_HIDP_MODULE 1
#define CPTCFG_BT_LE 1
#define CPTCFG_BT_HCIBTUSB_MODULE 1
#define CPTCFG_WLAN 1
#define CPTCFG_IWLWIFI_MODULE 1
#define CPTCFG_IWLWIFI_LEDS 1
#define CPTCFG_IWLDVM_MODULE 1
#define CPTCFG_IWLMVM_MODULE 1
#define CPTCFG_IWLWIFI_OPMODE_MODULAR 1
#define CPTCFG_IWLWIFI_DEBUG 1
#define CPTCFG_IWLWIFI_DEBUGFS 1
#define CPTCFG_IWLEGACY_MODULE 1
#define CPTCFG_IWL4965_MODULE 1
#define CPTCFG_IWL3945_MODULE 1
#define CPTCFG_IWLEGACY_DEBUGFS 1
#define CPTCFG_ETHERNET 1
#define CPTCFG_NET_VENDOR_ATHEROS 1
#define CPTCFG_NET_VENDOR_BROADCOM 1
#define CPTCFG_NET_VENDOR_INTEL 1
#define CPTCFG_USB_NET_DRIVERS_MODULE 1
#define CPTCFG_SSB_POSSIBLE 1
#define CPTCFG_BCMA_POSSIBLE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
