#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xce2547d6, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x7ccc02f9, __VMLINUX_SYMBOL_STR(skb_queue_head) },
	{ 0xddfc851c, __VMLINUX_SYMBOL_STR(release_sock) },
	{ 0x8c938b11, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x62b186c7, __VMLINUX_SYMBOL_STR(sock_init_data) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x69745e51, __VMLINUX_SYMBOL_STR(kernel_sendmsg) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xb43a926b, __VMLINUX_SYMBOL_STR(backport_dependency_symbol) },
	{ 0xb4fd8f60, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0x15692c87, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xc996d097, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xff1e7ece, __VMLINUX_SYMBOL_STR(single_release) },
	{ 0x4c86184b, __VMLINUX_SYMBOL_STR(remove_wait_queue) },
	{ 0xfa9c0857, __VMLINUX_SYMBOL_STR(bt_sock_poll) },
	{ 0x945a5816, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x7b6646bb, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x2cb16930, __VMLINUX_SYMBOL_STR(hci_register_cb) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x7d2c0224, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x4093b2be, __VMLINUX_SYMBOL_STR(bt_sock_ioctl) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x222f7b20, __VMLINUX_SYMBOL_STR(backport_wait_woken) },
	{ 0x1976aa06, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xdd1d5075, __VMLINUX_SYMBOL_STR(sock_create_kern) },
	{ 0x23d56250, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x9f587a65, __VMLINUX_SYMBOL_STR(bt_sock_register) },
	{ 0x12e4f8b7, __VMLINUX_SYMBOL_STR(kernel_listen) },
	{ 0x8e642281, __VMLINUX_SYMBOL_STR(debugfs_create_file) },
	{ 0xaa04d20c, __VMLINUX_SYMBOL_STR(hci_conn_check_secure) },
	{ 0xbccc037b, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0xe347dc36, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0xe9eb3a01, __VMLINUX_SYMBOL_STR(bt_sock_wait_state) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x47022514, __VMLINUX_SYMBOL_STR(bt_err) },
	{ 0xd7442057, __VMLINUX_SYMBOL_STR(bt_info) },
	{ 0xbf2a44f, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xe06141e9, __VMLINUX_SYMBOL_STR(security_sk_clone) },
	{ 0xacde6c9a, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xffd5a395, __VMLINUX_SYMBOL_STR(default_wake_function) },
	{ 0x3bfc937, __VMLINUX_SYMBOL_STR(bt_accept_enqueue) },
	{ 0x35ce0df2, __VMLINUX_SYMBOL_STR(bt_sock_unlink) },
	{ 0xe03f1f7b, __VMLINUX_SYMBOL_STR(bt_accept_unlink) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xd5f2172f, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0x36add587, __VMLINUX_SYMBOL_STR(skb_queue_purge) },
	{ 0x652c8b0c, __VMLINUX_SYMBOL_STR(bt_accept_dequeue) },
	{ 0xa9aacfd5, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xf869668b, __VMLINUX_SYMBOL_STR(kernel_connect) },
	{ 0x16005f85, __VMLINUX_SYMBOL_STR(sk_alloc) },
	{ 0x8438d80b, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xd5fb4626, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x82b2bdcc, __VMLINUX_SYMBOL_STR(lock_sock_nested) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xa58dee99, __VMLINUX_SYMBOL_STR(_raw_write_unlock) },
	{ 0xd702e480, __VMLINUX_SYMBOL_STR(_raw_read_unlock) },
	{ 0x51c67f4a, __VMLINUX_SYMBOL_STR(hci_conn_security) },
	{ 0xf5e84b7, __VMLINUX_SYMBOL_STR(debugfs_remove) },
	{ 0xbbbffe15, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xbb36d6f2, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x1ea06663, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x47d0d060, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x8834396c, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x8fea24bd, __VMLINUX_SYMBOL_STR(bt_sock_unregister) },
	{ 0x54fb8829, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0x214bae63, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xd906efd9, __VMLINUX_SYMBOL_STR(bt_sock_link) },
	{ 0xc4c5c757, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x939d362, __VMLINUX_SYMBOL_STR(skb_queue_tail) },
	{ 0xa6ffec60, __VMLINUX_SYMBOL_STR(woken_wake_function) },
	{ 0x60cfcb67, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0xdcfb5560, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xbc10dd97, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xea1f7a37, __VMLINUX_SYMBOL_STR(bt_debugfs) },
	{ 0xfe98ed27, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0xe35d5218, __VMLINUX_SYMBOL_STR(bt_sock_stream_recvmsg) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x38f13a17, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x9c4e3137, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0xacdd445e, __VMLINUX_SYMBOL_STR(hci_unregister_cb) },
	{ 0x6053998e, __VMLINUX_SYMBOL_STR(bt_sock_reclassify_lock) },
	{ 0x27ad8f26, __VMLINUX_SYMBOL_STR(sock_alloc_send_skb) },
	{ 0x63ded72a, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x7be29846, __VMLINUX_SYMBOL_STR(bt_sock_wait_ready) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x5af1db61, __VMLINUX_SYMBOL_STR(kernel_accept) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x8bd0a3fd, __VMLINUX_SYMBOL_STR(_raw_write_unlock_bh) },
	{ 0xc7bcbc8d, __VMLINUX_SYMBOL_STR(add_wait_queue) },
	{ 0xa4f169c9, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x22009c11, __VMLINUX_SYMBOL_STR(hci_conn_switch_role) },
	{ 0x9fb3dd30, __VMLINUX_SYMBOL_STR(memcpy_fromiovec) },
	{ 0x44d9e03e, __VMLINUX_SYMBOL_STR(set_user_nice) },
	{ 0xa414882d, __VMLINUX_SYMBOL_STR(add_wait_queue_exclusive) },
	{ 0x43529f11, __VMLINUX_SYMBOL_STR(kernel_bind) },
	{ 0x85061b76, __VMLINUX_SYMBOL_STR(_raw_write_lock_bh) },
	{ 0xac3ff705, __VMLINUX_SYMBOL_STR(bt_procfs_init) },
	{ 0xb70a16ae, __VMLINUX_SYMBOL_STR(skb_dequeue) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x24f9797b, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x6d044c26, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0xe3ff6c53, __VMLINUX_SYMBOL_STR(bt_procfs_cleanup) },
	{ 0x75be3dda, __VMLINUX_SYMBOL_STR(try_module_get) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=compat,bluetooth";


MODULE_INFO(srcversion, "CA23CFE415E811BC172FE58");
